version: '3'

services:
  web:
    hostname: woocommerce
    image: wordpress:php7.1-fpm-alpine
    environment:
      - WORDPRESS_DB_HOST=woocommerce_db_1
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=username
      - WORDPRESS_DB_PASSWORD=password
    ports:
      - 8080:9000
    links:
      - db
    networks:
      - docker_woocommerce

  db:
    hostname: mariadb
    image: mariadb
    command: mysqld --innodb-buffer-pool-size=20M
    volumes:
      - ./db:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpass
    ports:
      - 3306:3306
    networks:
      - docker_woocommerce

networks:
  docker_woocommerce:
    driver: bridge
