version: '3'

services:
  web:
    hostname: woocommerce
    image: junlapong/woocommerce
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
    networks:
      - network

  db:
    hostname: mariadb
    image: mariadb
    restart: always
    command: mysqld --innodb-buffer-pool-size=20M
    volumes:
      - ./data:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpass
    expose:
      - 3306
    networks:
      - network

networks:
  network:
    driver: bridge
